Repository favoritethings/web, pull requests merged in 2024-01, with the labels that each got.

#9 feat: impl modal component by using portal
  apps/client/src/app/layout.tsx
  apps/client/src/components/modal/index.tsx
Labels: ✨ feature

#11 fix: nodify merge resolve by mistake
  apps/client/src/app/layout.tsx
Labels: hotfix

#13 feat: add header nav bar
  apps/client/src/app/layout.tsx
  apps/client/src/app/page.tsx
  apps/client/src/components/layout/header/index.tsx
Labels: ✨ feature

#14 design: add home banner css
  apps/client/src/components/banner/index.tsx
Labels: ✨ feature

#12 feat: impl Steps Component
  apps/client/src/components/steps/index.tsx
Labels: ✨ feature

#15 design: add cration css design
  apps/client/next.config.js
  apps/client/src/components/curation/card/index.tsx
  apps/client/src/components/curation/header/index.tsx
  apps/client/src/components/curation/index.tsx
Labels: ✨ feature

#16 feat: inversion of control by using render prop pattern
  apps/client/src/components/steps/index.tsx
Labels: ✨ feature

#17 design: add footer layout
  apps/client/src/app/layout.tsx
  apps/client/src/components/layout/footer/index.tsx
Labels: 🎨 design

#18 fix: header component ul tag design edit
  apps/client/src/components/layout/header/index.tsx
Labels: 🎨 design

#23 style: join container component assembly
  apps/client/src/app/@modal/(.)auth/join/page.tsx
  apps/client/src/app/auth/join/container.tsx
  apps/client/src/app/auth/join/page.tsx
Labels: 🎨 design

#26 style: main banner image add and curation card svg add
  apps/client/src/components/banner/index.tsx
  apps/client/src/components/curation/card/index.tsx
  apps/client/src/components/curation/header/index.tsx
  apps/client/src/components/curation/index.tsx
Labels: 🎨 design

#30 feat: implement Tel Component
  apps/client/src/app/auth/join/container.tsx
  apps/client/src/components/form/input.tsx
Labels: ✨ feature

#32 style: implement Login Container Component
  apps/client/public/images/kakao.png
  apps/client/src/app/@modal/(.)auth/login/page.tsx
  apps/client/src/app/auth/login/container.tsx
  apps/client/src/app/auth/login/page.tsx
Labels: 🎨 design

#33 style: implement Checkbox and add insufficient style on Multi-Checkbox Component
  apps/client/src/app/auth/join/container.tsx
  apps/client/src/components/form/checkbox.tsx
  apps/client/src/components/form/input.tsx
  apps/client/src/components/form/multi-checkbox.tsx
Labels: 🎨 design

#34 feat: add login api on login container
  apps/client/src/app/api/member/action.ts
  apps/client/src/app/auth/login/container.tsx
Labels: ✨ feature
